backend:
  name: github
  repo: ordazgustavo/my-blog
  branch: master

media_folder: static/assets
public_folder: /assets

slug:
  encoding: 'ascii'
  clean_accents: true

collections:
  - name: post
    label: Posts
    folder: src/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Created at, widget: date }
      - { name: body, label: Post, widget: markdown }
      - { name: image, label: Image, widget: image }
      - { name: author, label: autor, default: Gustavo Ordaz }
      - { name: tags, label: Tags, widget: list, default: ['javascript'] }

  - name: page
    label: Pages
    folder: src/content/pages
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Post, widget: markdown }
      - { name: image, label: Image, widget: image }
